const SUPABASE_URL = 'https://cuglyictqzfjpkksqfjn.supabase.co';
const SUPABASE_KEY = 'sb_publishable_eE4FfeWwmToTk4hzS66jHw_UCFCLN0e';
const DATASET_URL = 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/data/exercises.json';
const MEDIA_NOTICE = 'La biblioteca textual puede integrarse según la licencia del repositorio. Los medios visuales externos no se muestran en esta versión.';
const APP_VERSION = '0.8.0';
const sb = window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY);

const demoExercises = [
  {id:'local-good-morning',name:'Buen día con disco',body_part:'upper legs',equipment:'disco',target:'isquiotibiales',secondary_muscles:['glúteos','zona media'],instructions:{es:'Realizá una bisagra de cadera manteniendo la espalda neutra. Llevá la cadera hacia atrás y volvé a la posición inicial controlando el movimiento.'},instruction_steps:{es:['Pies firmes al ancho aproximado de hombros.','Sostené el disco de manera segura.','Llevá la cadera hacia atrás sin redondear la espalda.','Volvé extendiendo la cadera y apretando glúteos.']},custom:true},
  {id:'local-row-plate',name:'Remo con disco',body_part:'back',equipment:'disco',target:'espalda',secondary_muscles:['bíceps','romboides'],instructions:{es:'Con el torso inclinado y espalda neutra, llevá el disco hacia el cuerpo y bajalo de forma controlada.'},instruction_steps:{es:['Adoptá una postura estable.','Incliná el torso conservando la espalda neutra.','Llevá el disco hacia el abdomen.','Juntá suavemente las escápulas y descendé controlado.']},custom:true},
  {id:'local-crunch',name:'Crunch con piernas arriba',body_part:'waist',equipment:'peso corporal / disco',target:'abdominales',secondary_muscles:['core'],instructions:{es:'Mantené las piernas elevadas y elevá el torso mediante una contracción abdominal sin tirar del cuello.'},instruction_steps:{es:['Acostate boca arriba y elevá las piernas.','Activá el abdomen.','Elevá el torso de forma corta y controlada.','Descendé sin perder tensión abdominal.']},custom:true},
  {id:'local-pullup',name:'Dominadas',body_part:'back',equipment:'barra',target:'dorsales',secondary_muscles:['bíceps','espalda alta'],instructions:{es:'Elevá el cuerpo desde la barra manteniendo control escapular y descendé de manera controlada.'},instruction_steps:{es:['Tomá la barra con agarre firme.','Activá hombros y abdomen.','Subí llevando el pecho hacia la barra.','Bajá controlando la extensión de los brazos.']},custom:true},
  {id:'local-trx-row',name:'Remo TRX',body_part:'back',equipment:'TRX',target:'espalda',secondary_muscles:['bíceps','core'],instructions:{es:'Con el cuerpo alineado, acercá el pecho a las manijas y extendé nuevamente los brazos.'},instruction_steps:{es:['Tomá las manijas y alineá el cuerpo.','Mantené abdomen activo.','Llevá el pecho hacia las manos.','Volvé de forma controlada.']},custom:true},
  {id:'local-deadlift',name:'Peso muerto sin rebote',body_part:'upper legs',equipment:'barra',target:'cadena posterior',secondary_muscles:['glúteos','isquiotibiales','espalda'],instructions:{es:'Levantá la carga mediante extensión de rodillas y cadera. Cada repetición se reinicia controlada, sin aprovechar rebote contra el piso.'},instruction_steps:{es:['Ubicá la carga cerca del cuerpo.','Fijá la espalda neutra y el abdomen.','Extendé cadera y rodillas hasta quedar erguido.','Descendé controlado y reiniciá sin rebote.']},custom:true},
  {id:'local-box-farmer',name:'Pasadas de cajón Farmer DB',body_part:'upper legs',equipment:'mancuernas + cajón',target:'piernas',secondary_muscles:['glúteos','agarre','core'],instructions:{es:'Sostené las mancuernas a los costados y realizá las pasadas/subidas al cajón con control.'},instruction_steps:{es:['Sostené una mancuerna en cada mano.','Asegurá el apoyo completo del pie en el cajón.','Subí manteniendo el torso estable.','Descendé con control y alterná según la consigna.']},custom:true},
  {id:'local-cleanjerk',name:'Hang Clean & Jerk alternado DB',body_part:'shoulders',equipment:'mancuerna',target:'cuerpo completo',secondary_muscles:['hombros','piernas','core'],instructions:{es:'Desde posición hang, llevá la mancuerna al hombro mediante el clean y luego sobre la cabeza con el jerk, alternando brazos.'},instruction_steps:{es:['Partí con la mancuerna desde hang.','Extendé la cadera y recibí la mancuerna en el hombro.','Impulsá y llevá la mancuerna sobre la cabeza.','Bloqueá arriba con control y alterná el brazo.']},custom:true},
  {id:'local-swing',name:'Swing americano con kettlebell',body_part:'upper legs',equipment:'kettlebell',target:'glúteos',secondary_muscles:['isquiotibiales','hombros','core'],instructions:{es:'Generá el impulso desde la cadera y acompañá la kettlebell hasta arriba de la cabeza.'},instruction_steps:{es:['Iniciá con una bisagra de cadera.','Llevá la kettlebell entre las piernas.','Extendé fuerte la cadera.','Acompañá el recorrido hasta arriba y controlá el regreso.']},custom:true},
  {id:'local-vups',name:'V-Ups',body_part:'waist',equipment:'peso corporal',target:'abdominales',secondary_muscles:['flexores de cadera'],instructions:{es:'Elevá simultáneamente torso y piernas buscando acercar manos y pies.'},instruction_steps:{es:['Partí extendido boca arriba.','Activá el abdomen.','Elevá piernas y torso a la vez.','Descendé de manera controlada.']},custom:true},
  {id:'local-plank-alt',name:'Plancha alternada',body_part:'waist',equipment:'peso corporal',target:'core',secondary_muscles:['hombros','glúteos'],instructions:{es:'Mantené una plancha firme y realizá la variante alternada indicada sin perder la posición de la cadera.'},instruction_steps:{es:['Alineá hombros, cadera y tobillos.','Activá abdomen y glúteos.','Realizá el gesto alternado indicado.','Evitá rotar la cadera en exceso.']},custom:true},
  {id:'local-tuck',name:'Abdominal bolita',body_part:'waist',equipment:'peso corporal',target:'abdominales',secondary_muscles:['flexores de cadera'],instructions:{es:'Acercá simultáneamente rodillas y torso y volvé a extender con control.'},instruction_steps:{es:['Partí extendido.','Flexioná rodillas hacia el pecho.','Acercá el torso manteniendo control abdominal.','Volvé a extender sin perder tensión.']},custom:true},
  {id:'local-plate-jumping-jack',name:'Jumping Jack con disco',body_part:'cardio',equipment:'disco',target:'activación general',secondary_muscles:['hombros','piernas','core'],instructions:{es:'Abrí las piernas mientras elevás el disco con los brazos y volvé a juntar de forma coordinada.'},instruction_steps:{es:['Sostené el disco con ambas manos.','Abrí las piernas con un pequeño salto mientras elevás el disco.','Mantené el abdomen activo.','Volvé a juntar piernas y bajar el disco con control.']},custom:true},
  {id:'local-seated-shoulder-press',name:'Press de hombros sentado',body_part:'shoulders',equipment:'mancuernas / disco',target:'hombros',secondary_muscles:['tríceps','core'],instructions:{es:'Desde sentado, empujá la carga por encima de la cabeza y descendé con control.'},instruction_steps:{es:['Sentate estable con el torso erguido.','Ubicá la carga a la altura de hombros.','Empujá hacia arriba sin arquear de más la espalda.','Bajá de forma controlada.']},custom:true},
  {id:'local-cross-toe-touch',name:'Abdominal cruzado mano-pie',body_part:'waist',equipment:'peso corporal',target:'abdominales',secondary_muscles:['oblicuos','flexores de cadera'],instructions:{es:'Desde extendido, acercá una mano a la punta del pie contrario y alterná lados.'},instruction_steps:{es:['Partí acostado y extendido.','Elevá una pierna y el torso.','Buscá tocar la punta del pie con la mano contraria.','Volvé con control y alterná.']},custom:true},
  {id:'local-ground-to-overhead',name:'Ground to Overhead con barra',body_part:'shoulders',equipment:'barra',target:'cuerpo completo',secondary_muscles:['piernas','espalda','hombros','core'],instructions:{es:'Llevá la barra desde el piso hasta una posición estable por encima de la cabeza usando la variante indicada por el profesor.'},instruction_steps:{es:['Prepará la salida con la barra cerca del cuerpo.','Extendé piernas y cadera manteniendo control.','Llevá la barra por encima de la cabeza según la técnica indicada.','Finalizá estable y bajá de forma segura.']},custom:true},
  {id:'local-pushup',name:'Flexiones',body_part:'chest',equipment:'peso corporal',target:'pecho',secondary_muscles:['tríceps','hombros','core'],instructions:{es:'Descendé el cuerpo en bloque y empujá el piso manteniendo alineación.'},instruction_steps:{es:['Manos firmes debajo o apenas más abiertas que los hombros.','Mantené abdomen y glúteos activos.','Descendé controlando el torso.','Empujá hasta volver a la posición inicial.']},custom:true},
  {id:'local-burpee-tuck',name:'Burpee + Tuck Jump (burpee bastardo)',body_part:'cardio',equipment:'peso corporal',target:'acondicionamiento',secondary_muscles:['piernas','pecho','core'],instructions:{es:'Realizá un burpee y terminá con un salto llevando las rodillas hacia el pecho.'},instruction_steps:{es:['Bajá al piso para realizar el burpee.','Volvé a la posición de pie con control.','Saltá llevando las rodillas hacia el pecho.','Aterrizá suave y preparate para la siguiente repetición.']},custom:true},
  {id:'local-db-cleanjerk-floor',name:'DB Clean & Jerk alternado desde piso',body_part:'shoulders',equipment:'mancuerna',target:'cuerpo completo',secondary_muscles:['piernas','hombros','core'],instructions:{es:'Llevá la mancuerna desde el piso al hombro y luego por encima de la cabeza. Alterná el brazo según la consigna.'},instruction_steps:{es:['Tomá la mancuerna desde el piso con postura firme.','Usá piernas y cadera para llevarla al hombro.','Impulsá la mancuerna por encima de la cabeza.','Bajá con control y realizá el cambio de brazo como indique el profesor.']},custom:true},
  {id:'local-hand-walk',name:'Caminata de manos / Inchworm',body_part:'waist',equipment:'peso corporal',target:'core y hombros',secondary_muscles:['isquiotibiales','pecho'],instructions:{es:'Desde parado, apoyá las manos y caminá con ellas hacia adelante y atrás manteniendo control del tronco.'},instruction_steps:{es:['Inclinate y apoyá las manos en el piso.','Caminá con las manos hacia una posición extendida.','Mantené el abdomen activo.','Regresá con las manos y reincorporate con control.']},custom:true}
];

const sampleWorkout = {
  format:'blocks',
  reps:'15 · 12 · 9 · 5 · 3',
  activation:['local-good-morning','local-row-plate','local-crunch'],
  blocks:[
    {name:'A',tc:6,rest:1,exercises:['local-pullup','local-trx-row','local-deadlift']},
    {name:'B',tc:6,rest:1,exercises:['local-box-farmer','local-cleanjerk']},
    {name:'C',tc:6,rest:1,exercises:['local-swing']},
    {name:'D',tc:6,rest:0,exercises:['local-plank-alt','local-vups','local-tuck']}
  ]
};

const stationWorkoutPreset = {
  format:'stations',
  reps:'',
  activation:[
    {id:'local-plate-jumping-jack',reps:'6'},
    {id:'local-seated-shoulder-press',reps:'6'},
    {id:'local-cross-toe-touch',reps:'6'}
  ],
  stations:[
    {name:'Estación 1',duration:3,note:'Repetir 3 + 3 durante los 3 minutos.',exercises:[{id:'local-ground-to-overhead',reps:'3'},{id:'local-pushup',reps:'3'}]},
    {name:'Estación 2',duration:3,note:'Pendiente de completar.',exercises:[]},
    {name:'Estación 3',duration:3,note:'Alternar el brazo en el movimiento con mancuerna.',exercises:[{id:'local-db-cleanjerk-floor',reps:'3'},{id:'local-hand-walk',reps:'6'}]}
  ],
  joker:{enabled:true,every:1,unit:'min',exercise:{id:'local-burpee-tuck',reps:'1'},instruction:'Cada 1 minuto: pausar la estación, hacer el comodín y retomar donde se dejó.'}
};

const routinePresets = [
  {name:'15-12-9-5-3 · WOD por bloques',description:'Activación + cuatro WOD con Time Cap y descanso.',title:'15-12-9-5-3',intro:'Rutina por bloques.',payload:sampleWorkout},
  {name:"Estaciones 3' + comodín cada 1'",description:'Rutina reconstruida de la clase del 26/08. La estación 2 queda pendiente.',title:"Estaciones 3' + comodín",intro:'Estaciones de 3 minutos con interrupción de comodín cada minuto.',payload:stationWorkoutPreset}
];

const state = {
  session:null,user:null,profile:null,guest:false,view:'home',selectedDay:localDay(0),
  sessions:[],myReservations:[],templates:[],weekdays:[],attendees:{},workout:null,workoutHistory:[],routineTemplates:[],
  dataset:demoExercises,datasetLoaded:false,query:'',filter:'todos',equipmentFilter:'todos',libraryMode:'all',modal:null,previewRoutine:null,
  customExercises:[],aliases:[],favorites:[],recentExercises:loadLocalList('entrena-recent-exercises'),
  busy:false,message:null,adminTab:'overview',builderSearch:'',builderTarget:'activation',
  draft:null,draftDay:null,dragInfo:null
};

function localDay(add=0){const d=new Date();d.setDate(d.getDate()+add);const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function h(v=''){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmtTime(t){return (t||'').slice(0,5)}
function fmtDay(s){if(!s)return'';const [y,m,d]=s.split('-').map(Number);return new Intl.DateTimeFormat('es-AR',{weekday:'short',day:'2-digit',month:'2-digit'}).format(new Date(y,m-1,d))}
function isStaff(){return ['coach','admin'].includes(state.profile?.role)}
function exById(id){return state.dataset.find(x=>x.id===id)||demoExercises.find(x=>x.id===id)}
function iconFor(ex){const p=ex?.body_part;return p==='back'?'🪽':p==='waist'?'🔥':p==='shoulders'?'💪':p==='upper legs'?'🦵':p==='cardio'?'❤️':p==='chest'?'🏋️':'🏃'}
function setMessage(text,type='notice'){state.message={text,type};render();setTimeout(()=>{state.message=null;render()},3200)}

function loadLocalList(key){try{const v=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(v)?v:[]}catch{return []}}
function saveLocalList(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
function favoriteSet(){return new Set(state.favorites||[])}
function isFavorite(id){return favoriteSet().has(id)}
function aliasesFor(id){return (state.aliases||[]).filter(a=>a.exercise_key===id).map(a=>a.alias)}
function touchRecent(id){state.recentExercises=[id,...(state.recentExercises||[]).filter(x=>x!==id)].slice(0,16);saveLocalList('entrena-recent-exercises',state.recentExercises)}
function openExercise(id){const ex=exById(id);if(!ex)return;touchRecent(id);state.modal=ex;render()}
function customRowToExercise(x){return {id:`db-${x.id}`,db_id:x.id,name:x.name,body_part:x.body_part||'',equipment:x.equipment||'',target:x.target||'',secondary_muscles:[],instructions:{es:x.instructions||''},instruction_steps:{es:Array.isArray(x.steps)?x.steps:[]},custom:true,dbCustom:true}}
function applyExerciseSources(){const gh=(state.dataset||[]).filter(x=>String(x.id).startsWith('gh-'));state.dataset=[...demoExercises,...(state.customExercises||[]).map(customRowToExercise),...gh]}
async function loadExerciseLibraryMeta(){
  const tasks=[sb.from('custom_exercises').select('id,name,body_part,target,equipment,instructions,steps,active').eq('active',true).order('name'),sb.from('exercise_aliases').select('alias,exercise_key').eq('active',true).order('alias')];
  if(state.user)tasks.push(sb.from('exercise_favorites').select('exercise_key').eq('user_id',state.user.id));
  const res=await Promise.all(tasks);state.customExercises=res[0].data||[];state.aliases=res[1].data||[];state.favorites=state.user?(res[2]?.data||[]).map(x=>x.exercise_key):loadLocalList('entrena-favorites-guest');applyExerciseSources();
}
async function toggleFavorite(id){
  const fav=isFavorite(id);
  if(state.user){const q=fav?sb.from('exercise_favorites').delete().eq('user_id',state.user.id).eq('exercise_key',id):sb.from('exercise_favorites').insert({user_id:state.user.id,exercise_key:id});const {error}=await q;if(error)return setMessage('No pude actualizar favoritos.','notice warning')}
  state.favorites=fav?(state.favorites||[]).filter(x=>x!==id):[id,...(state.favorites||[])];if(!state.user)saveLocalList('entrena-favorites-guest',state.favorites);render();
}
function equipmentMatches(ex,key){if(key==='todos')return true;const e=(ex.equipment||'').toLowerCase();const map={barra:['barra'],mancuerna:['mancuerna','mancuernas','db'],kettlebell:['kettlebell','kb'],disco:['disco'],trx:['trx'],corporal:['peso corporal','corporal'],cajon:['cajón','cajon']};return (map[key]||[key]).some(v=>e.includes(v))}

function blockByName(name){return state.draft?.blocks?.find(b=>b.name===name)}
function cloneData(v){return JSON.parse(JSON.stringify(v))}
function normalizeItem(v){if(typeof v==='string')return {id:v,reps:'',load:'',note:''};return {id:v?.id||'',reps:String(v?.reps??''),load:String(v?.load??''),note:String(v?.note??'')}}
function itemId(v){return typeof v==='string'?v:(v?.id||'')}
function itemReps(v){return typeof v==='string'?'':String(v?.reps??'')}
function itemLoad(v){return typeof v==='string'?'':String(v?.load??'')}
function itemNote(v){return typeof v==='string'?'':String(v?.note??'')}
function normalizeItems(list){return (list||[]).map(normalizeItem).filter(x=>x.id)}
function emptyBlocks(){return ['A','B','C','D'].map((name,i)=>({name,tc:6,rest:i===3?0:1,exercises:[]}))}
function emptyMain(){return {duration:12,rounds:'',work:40,rest:20,note:'',exercises:[]}}
function emptyDraft(){return {title:'Entrenamiento del día',intro:'',format:'blocks',reps:'',activation:[],blocks:emptyBlocks(),stations:[{name:'Estación 1',duration:3,note:'',exercises:[]}],joker:{enabled:false,every:1,unit:'min',exercise:null,instruction:'Al cumplirse el intervalo, pausá la estación, hacé el comodín y retomá.'},main:emptyMain(),published:false}}
function draftFromRow(row){if(!row)return emptyDraft();const p=row.payload||{};const format=p.format||(Array.isArray(p.stations)?'stations':'blocks');return {title:row.title||'Entrenamiento del día',intro:row.intro||'',format,reps:p.reps||'',activation:normalizeItems(p.activation),blocks:['A','B','C','D'].map((name,i)=>{const src=(p.blocks||[]).find(b=>String(b.name).toUpperCase()===name);return {name,tc:Number(src?.tc??6),rest:Number(src?.rest??(i===3?0:1)),exercises:normalizeItems(src?.exercises)}}),stations:(p.stations||[]).map((s,i)=>({name:s.name||`Estación ${i+1}`,duration:Number(s.duration||3),note:s.note||'',exercises:normalizeItems(s.exercises)})),joker:{enabled:!!p.joker?.enabled,every:Number(p.joker?.every||1),unit:p.joker?.unit||'min',exercise:p.joker?.exercise?normalizeItem(p.joker.exercise):null,instruction:p.joker?.instruction||'Al cumplirse el intervalo, pausá la estación, hacé el comodín y retomá.'},main:{...emptyMain(),...(p.main||{}),exercises:normalizeItems(p.main?.exercises)},published:!!row.published}}
function draftFromWorkout(){return draftFromRow(state.workout)}
function ensureDraft(force=false){if(force||state.draftDay!==state.selectedDay||!state.draft){state.draft=draftFromWorkout();state.draftDay=state.selectedDay}}
function draftFromPreset(preset){const d=draftFromRow({title:preset.title,intro:preset.intro,payload:preset.payload,published:false});d.published=false;return d}
function isSimpleFormat(format){return ['amrap','emom','fortime','tabata','free'].includes(format)}
function formatName(format){return ({blocks:'WOD por bloques',stations:'Estaciones',amrap:'AMRAP',emom:'EMOM',fortime:'For Time',tabata:'Tabata',free:'Libre'})[format]||'Rutina'}
function payloadFromDraft(d){const payload={format:d.format,reps:d.reps||'',activation:normalizeItems(d.activation)};if(d.format==='stations'){payload.stations=(d.stations||[]).map(s=>({name:s.name||'Estación',duration:Number(s.duration||3),note:s.note||'',exercises:normalizeItems(s.exercises)}));payload.joker={enabled:!!d.joker.enabled,every:Number(d.joker.every||1),unit:'min',exercise:d.joker.exercise?normalizeItem(d.joker.exercise):null,instruction:d.joker.instruction||''}}else if(d.format==='blocks'){payload.blocks=(d.blocks||[]).map(b=>({name:b.name,tc:Number(b.tc||0),rest:Number(b.rest||0),exercises:normalizeItems(b.exercises)}))}else{payload.main={duration:Number(d.main?.duration||0),rounds:String(d.main?.rounds||''),work:Number(d.main?.work||0),rest:Number(d.main?.rest||0),note:d.main?.note||'',exercises:normalizeItems(d.main?.exercises)}}return payload}
function draftHasExercises(d){return !!(d.activation?.length||(d.format==='stations'?(d.stations||[]).some(s=>s.exercises?.length)||!!d.joker?.exercise:d.format==='blocks'?(d.blocks||[]).some(b=>b.exercises?.length):d.main?.exercises?.length))}

async function init(){
  const {data:{session}}=await sb.auth.getSession();
  state.session=session;state.user=session?.user||null;
  if(state.user)await loadProfile();
  await loadExerciseLibraryMeta();
  await refreshPublic();
  sb.auth.onAuthStateChange(async(_event,session)=>{state.session=session;state.user=session?.user||null;if(state.user)await loadProfile();else state.profile=null;await loadExerciseLibraryMeta();await refreshPublic();render()});
  render();
}

async function loadProfile(){const {data,error}=await sb.from('profiles').select('id,full_name,role,active').eq('id',state.user.id).maybeSingle();if(error)console.error(error);state.profile=data||null}

async function loadWorkoutHistory(){
  if(!isStaff()){state.workoutHistory=[];return}
  const {data,error}=await sb.from('workouts').select('id,day,title,intro,payload,published,updated_at').order('day',{ascending:false}).limit(20);
  if(error){console.error(error);state.workoutHistory=[];return}
  state.workoutHistory=data||[];
}

async function loadRoutineTemplates(){
  if(!isStaff()){state.routineTemplates=[];return}
  const {data,error}=await sb.from('routine_templates').select('id,name,description,payload,created_at,updated_at').eq('active',true).order('updated_at',{ascending:false}).limit(30);
  if(error){console.error(error);state.routineTemplates=[];return}
  state.routineTemplates=data||[];
}

async function refreshPublic(){
  const [{data:sessions,error:se},{data:templates,error:te},{data:weekdays,error:wde},{data:workouts,error:we}]=await Promise.all([
    sb.from('class_sessions').select('id,template_id,class_date,label,start_time,end_time,capacity,is_open,confirmed_count,waitlist_count').eq('class_date',state.selectedDay).order('start_time'),
    sb.from('class_templates').select('*').order('sort_order'),
    sb.from('class_weekdays').select('iso_day,label,active').order('iso_day'),
    sb.from('workouts').select('*').eq('day',state.selectedDay).maybeSingle()
  ]);
  if(se)console.error(se);if(te)console.error(te);if(wde)console.error(wde);if(we)console.error(we);
  state.sessions=(sessions||[]).map(s=>({...s,spots_left:Math.max((s.capacity||0)-(s.confirmed_count||0),0)}));
  state.templates=templates||[];state.weekdays=weekdays||[];state.workout=workouts||null;state.myReservations=[];state.attendees={};
  if(state.user&&state.sessions.length){
    const ids=state.sessions.map(s=>s.id);
    const {data:r,error}=await sb.from('reservations').select('session_id,status,user_id,created_at').in('session_id',ids);
    if(error)console.error(error);
    state.myReservations=(r||[]).filter(x=>x.user_id===state.user.id);
    if(isStaff())await loadAttendees(r||[]);
  }
  if(isStaff()){await Promise.all([loadWorkoutHistory(),loadRoutineTemplates()]);ensureDraft();}
}


async function loadAttendees(reservations){
  const active=reservations.filter(r=>r.status!=='cancelled');const ids=[...new Set(active.map(r=>r.user_id))];let profiles=[];
  if(ids.length){const {data}=await sb.from('profiles').select('id,full_name').in('id',ids);profiles=data||[]}
  const names=Object.fromEntries(profiles.map(p=>[p.id,p.full_name]));state.attendees={};
  for(const r of active)(state.attendees[r.session_id]||=[]).push({...r,name:names[r.user_id]||'Alumno',source:'user'});
  const sessionIds=state.sessions.map(s=>s.id);
  if(sessionIds.length){
    const {data:manual,error}=await sb.from('manual_reservations').select('id,session_id,display_name,status,created_at').in('session_id',sessionIds).neq('status','cancelled').order('created_at');
    if(error)console.error(error);
    for(const m of (manual||[]))(state.attendees[m.session_id]||=[]).push({...m,name:m.display_name,source:'manual'});
  }
}

function authScreen(){return `<div class="login-wrap"><div class="login-card"><div class="login-logo">E</div><h1>ENTRENA</h1><p>Reservá tu turno y consultá los ejercicios desde el celular. No hace falta instalar una app.</p>${state.message?`<div class="${state.message.type}">${h(state.message.text)}</div>`:''}<div class="filters" style="margin:14px 0 8px"><button class="chip active" data-auth-tab="login">Ingresar</button><button class="chip" data-auth-tab="signup">Crear cuenta</button></div><form id="authForm" class="form-grid" data-mode="login"><div class="field signup-only" style="display:none"><label>Nombre y apellido</label><input name="full_name" autocomplete="name" /></div><div class="field"><label>Correo</label><input name="email" type="email" required autocomplete="email" /></div><div class="field"><label>Contraseña</label><input name="password" type="password" minlength="6" required autocomplete="current-password" /></div><button class="primary-btn" type="submit">Ingresar</button></form><button class="ghost-btn" style="width:100%;margin-top:10px" data-action="guest">Mirar sin cuenta</button><div class="login-hint">Para reservar necesitás cuenta. El manual y los ejercicios se pueden mirar sin registrarse.</div></div></div>`}
function topbar(){return `<header class="topbar"><div class="topbar-inner"><div class="brand"><div class="brand-badge">E</div><div>ENTRENA<small>${isStaff()?'Panel profesor':state.profile?.full_name||'Modo consulta'} · <span class="version">v${APP_VERSION}</span></small></div></div><button class="icon-btn" data-view="profile">👤</button></div></header>`}
function nav(){const n=[['home','🏠','Inicio'],['slots','📅','Turnos'],['library','🏋️','Ejercicios'],['manual','📖','Manual'],[isStaff()?'admin':'profile',isStaff()?'⚙️':'👤',isStaff()?'Profe':'Perfil']];return `<nav class="bottom-nav"><div class="bottom-nav-inner">${n.map(([v,i,l])=>`<button class="nav-btn ${state.view===v?'active':''}" data-view="${v}"><span>${i}</span>${l}</button>`).join('')}</div></nav>`}
function dateStrip(){return `<div class="filters" style="margin-top:12px">${[0,1,2,3,4,5,6].map(n=>{const d=localDay(n);return `<button class="chip ${state.selectedDay===d?'active':''}" data-day="${d}">${n===0?'Hoy':n===1?'Mañana':fmtDay(d)}</button>`}).join('')}</div>`}
function messageBar(){return state.message?`<div class="${state.message.type}" style="margin-top:12px">${h(state.message.text)}</div>`:''}

function slotCard(s,compact=false){
  const mine=state.myReservations.find(r=>r.session_id===s.id&&r.status!=='cancelled');
  const other=state.myReservations.find(r=>r.session_id!==s.id&&r.status!=='cancelled');
  const pct=Math.min(100,Math.round((s.confirmed_count/s.capacity)*100));const closed=!s.is_open;const full=s.spots_left<=0;let action='';
  if(mine)action=`<button class="danger-btn" data-cancel="${s.id}">${mine.status==='waitlist'?'Salir de espera':'Cancelar'}</button>`;
  else if(state.user&&other)action=`<button class="primary-btn" data-change-reservation="${s.id}" ${closed?'disabled':''}>${closed?'Cerrado':full?'Cambiarme · espera':'Cambiarme acá'}</button>`;
  else if(state.user)action=`<button class="primary-btn" data-reserve="${s.id}" ${closed?'disabled':''}>${closed?'Cerrado':full?'Lista de espera':'Anotarme'}</button>`;
  else action=`<button class="primary-btn" data-action="need-login">Anotarme</button>`;
  return `<article class="card slot"><div><div class="slot-title">${fmtTime(s.start_time)} — ${fmtTime(s.end_time)}</div><div class="slot-meta">${h(s.label)} · ${s.confirmed_count}/${s.capacity} anotados${s.waitlist_count?` · ${s.waitlist_count} en espera`:''}${closed?' · cerrado':''}</div><div class="capacity ${full?'full':''}"><span style="width:${pct}%"></span></div>${mine?`<div class="section-sub" style="margin-top:8px">${mine.status==='confirmed'?'✅ Tenés tu lugar':'⏳ Estás en lista de espera'}</div>`:other&&!compact?`<div class="section-sub" style="margin-top:8px">Ya tenés otro horario: podés cambiarte con un toque.</div>`:''}</div>${compact?`<div class="kpi"><strong>${s.spots_left}</strong>libres</div>`:action}</article>`
}
function exerciseRow(ex,reps='',load='',note=''){if(!ex)return'';const meta=[ex.target||'',ex.equipment||'',load?`Carga: ${load}`:''].filter(Boolean).join(' · ');return `<div class="exercise-row"><div><div class="exercise-name">${reps?`<span class="rep-badge">${h(reps)}</span> `:''}${h(ex.name)}</div><div class="exercise-note">${h(meta)}</div>${note?`<div class="exercise-coach-note">📝 ${h(note)}</div>`:''}</div><button class="mini-btn" data-exercise="${h(ex.id)}">Ver</button></div>`}
function workoutItemRow(item){const ex=exById(itemId(item));return exerciseRow(ex,itemReps(item),itemLoad(item),itemNote(item))}
function simpleSummary(format,main){if(format==='amrap')return `${Number(main.duration||0)} min · mayor cantidad de rondas/reps`;if(format==='emom')return `${Number(main.duration||0)} min · trabajo al inicio de cada minuto`;if(format==='fortime')return `${main.rounds?`${h(main.rounds)} rondas · `:''}${Number(main.duration||0)?`TC ${Number(main.duration)} min`:'completar lo indicado'}`;if(format==='tabata')return `${Number(main.work||20)}s trabajo · ${Number(main.rest||10)}s descanso${main.rounds?` · ${h(main.rounds)} rondas`:''}`;return main.note||'Formato libre'}
function sampleWorkoutHtml(payload=sampleWorkout,title='Rutina de ejemplo',intro=''){
  const act=normalizeItems(payload.activation);const format=payload.format||(Array.isArray(payload.stations)?'stations':'blocks');
  let body='';
  if(format==='stations'){
    const stations=payload.stations||[];const joker=payload.joker||{};
    body=`${stations.map((s,i)=>`<div class="station-display"><div class="section-head"><div><h2>${h(s.name||`Estación ${i+1}`)}</h2><div class="section-sub">${h(s.note||'')}</div></div><span class="pill">${Number(s.duration||3)} min</span></div>${normalizeItems(s.exercises).map(workoutItemRow).join('')||'<div class="section-sub">Estación pendiente de completar.</div>'}</div>`).join('')}${joker.enabled?`<div class="joker-display"><div class="section-head"><div><h2>⚡ Comodín</h2><div class="section-sub">${h(joker.instruction||'Interrumpí la estación, hacé el comodín y retomá.')}</div></div><span class="pill">cada ${Number(joker.every||1)} min</span></div>${joker.exercise?workoutItemRow(joker.exercise):'<div class="section-sub">Sin ejercicio cargado.</div>'}</div>`:''}`;
  }else if(format==='blocks'){
    const blocks=payload.blocks||[];
    body=blocks.map(b=>`<div style="margin-top:16px"><div class="section-head"><h2>WOD ${h(b.name)}</h2><span class="pill">TC ${Number(b.tc||0)}'${Number(b.rest||0)?` · REST ${Number(b.rest)}'`:''}</span></div>${normalizeItems(b.exercises).map(workoutItemRow).join('')||'<div class="section-sub">Sin ejercicios.</div>'}</div>`).join('');
  }else{
    const main=payload.main||{};
    body=`<div class="simple-display"><div class="section-head"><div><h2>${h(formatName(format))}</h2><div class="section-sub">${h(main.note||'')}</div></div><span class="pill">${simpleSummary(format,main)}</span></div>${normalizeItems(main.exercises).map(workoutItemRow).join('')||'<div class="section-sub">Sin ejercicios cargados.</div>'}</div>`;
  }
  return `<article class="card"><div class="workout-header"><div class="workout-icon">🔥</div><div><div class="workout-title">${h(title)}</div><div class="workout-reps">${h(payload.reps||'')}</div></div></div>${intro?`<p class="muted">${h(intro)}</p>`:''}<div class="format-label">${h(formatName(format).toUpperCase())}</div><h2 style="margin-top:18px">Activación</h2>${act.length?act.map(workoutItemRow).join(''):'<div class="section-sub" style="padding:10px 0">Sin ejercicios cargados.</div>'}${body}</article>`
}

function homeView(){
  const real=!!state.workout&&state.workout.published!==false;const payload=real?state.workout.payload:sampleWorkout;const title=real?state.workout.title:'Ejemplo de rutina';const intro=real?state.workout.intro:'Cuando el profesor publique la rutina del día aparecerá acá.';
  return `<section class="hero"><div class="hero-row"><div><h1>${state.profile?`Hola, ${h((state.profile.full_name||'').split(' ')[0])}`:'Entrenamiento'}</h1><p>Elegí el horario que te quede cómodo y revisá la rutina antes de la clase.</p></div><span class="pill">${fmtDay(state.selectedDay)}</span></div>${dateStrip()}</section>${messageBar()}<section class="section"><div class="section-head"><div><h2>Turnos</h2><div class="section-sub">Cupos actualizados para el día elegido</div></div><button class="mini-btn" data-view="slots">Ver todos</button></div><div class="grid">${state.sessions.length?state.sessions.slice(0,2).map(s=>slotCard(s,true)).join(''):'<div class="empty card">Todavía no hay turnos habilitados para este día.</div>'}</div></section><section class="section"><div class="section-head"><div><h2>${real?'Entrenamiento del día':'Manual de ejemplo'}</h2><div class="section-sub">Tocá un ejercicio para ver cómo se realiza</div></div>${isStaff()?'<button class="mini-btn" data-admin-tab="workout">Editar</button>':''}</div>${sampleWorkoutHtml(payload,title,intro)}</section>`
}
function slotsView(){return `<section class="hero"><h1>Reservar turno</h1><p>Elegí el día y reservá un solo horario. Si no vas a poder ir, cancelalo para liberar el cupo.</p>${dateStrip()}</section>${messageBar()}<section class="section"><div class="grid">${state.sessions.length?state.sessions.map(s=>slotCard(s)).join(''):`<div class="empty card">No hay turnos habilitados para ${fmtDay(state.selectedDay)}.${isStaff()?'<br><br><button class="primary-btn" data-action="generate-day">Habilitar turnos del día</button>':''}</div>`}</div></section>`}
function libraryView(){
  const items=filteredExercises(state.query,state.filter,true).slice(0,100);
  const filters=[['todos','Todos'],['back','Espalda'],['upper legs','Piernas'],['waist','Abdomen'],['shoulders','Hombros'],['chest','Pecho'],['cardio','Cardio']];
  const eq=[['todos','Todo equipo'],['barra','Barra'],['mancuerna','DB'],['kettlebell','KB'],['disco','Disco'],['trx','TRX'],['corporal','Corporal'],['cajon','Cajón']];
  const modes=[['all','Todos'],['favorites','⭐ Favoritos'],['recent','🕘 Recientes']];
  const cards=items.map(ex=>`<article class="card exercise-card pro-exercise-card"><button class="favorite-btn ${isFavorite(ex.id)?'active':''}" data-favorite="${h(ex.id)}" title="Favorito">${isFavorite(ex.id)?'★':'☆'}</button><div class="exercise-thumb">${iconFor(ex)}</div><div><div class="exercise-name">${h(ex.name)}</div><div class="section-sub">${h(ex.target||'')} · ${h(ex.equipment||'')}</div>${aliasesFor(ex.id).length?`<div class="alias-line">También: ${aliasesFor(ex.id).slice(0,3).map(h).join(' · ')}</div>`:''}</div><button class="mini-btn" data-exercise="${h(ex.id)}">Ver</button></article>`).join('');
  const custom=isStaff()?`<section class="section"><article class="card"><div class="section-head"><div><h2>➕ Ejercicio propio</h2><div class="section-sub">Queda guardado en la biblioteca del gimnasio.</div></div></div><form id="customExerciseForm" class="form-grid"><div class="two"><div class="field"><label>Nombre</label><input name="name" required placeholder="Ej: Remo invertido"></div><div class="field"><label>Zona</label><select name="body_part"><option value="back">Espalda</option><option value="upper legs">Piernas</option><option value="waist">Abdomen</option><option value="shoulders">Hombros</option><option value="chest">Pecho</option><option value="cardio">Cardio</option></select></div></div><div class="two"><div class="field"><label>Objetivo</label><input name="target" placeholder="dorsales, core..."></div><div class="field"><label>Elemento</label><input name="equipment" placeholder="barra, DB, TRX..."></div></div><div class="field"><label>Sinónimos / nombres de clase</label><input name="aliases" placeholder="separados por coma"></div><div class="field"><label>Explicación</label><textarea name="instructions" placeholder="Cómo se realiza"></textarea></div><div class="field"><label>Pasos (uno por línea)</label><textarea name="steps" placeholder="Posición inicial
Movimiento
Final"></textarea></div><button class="primary-btn" type="submit">Guardar ejercicio</button></form></article></section>`:'';
  return `<section class="hero"><h1>Biblioteca PRO</h1><p>Favoritos, recientes, sinónimos y filtros por elemento. Buscá como lo nombran en clase: por ejemplo “burpee bastardo”.</p></section><section class="section"><div class="filters">${modes.map(([k,l])=>`<button class="chip ${state.libraryMode===k?'active':''}" data-library-mode="${k}">${l}</button>`).join('')}</div><input id="exerciseSearch" class="search" placeholder="Buscar: burpee bastardo, peso muerto, mancuerna..." value="${h(state.query)}"><div class="filters" style="margin-top:10px">${filters.map(([k,l])=>`<button class="chip ${state.filter===k?'active':''}" data-filter="${k}">${l}</button>`).join('')}</div><div class="filters">${eq.map(([k,l])=>`<button class="chip ${state.equipmentFilter===k?'active':''}" data-equipment-filter="${k}">${l}</button>`).join('')}</div><div class="notice warning">${MEDIA_NOTICE}</div><button class="${state.datasetLoaded?'ghost-btn':'primary-btn'}" style="margin-top:10px" data-action="load-dataset">${state.datasetLoaded?'Base completa cargada':'Cargar base completa (~17 MB)'}</button></section><section class="section"><div class="section-head"><div><h2>${state.libraryMode==='favorites'?'Favoritos':state.libraryMode==='recent'?'Usados recientemente':'Ejercicios'}</h2><div class="section-sub">${items.length} coincidencias</div></div></div><div class="grid cols2">${cards||'<div class="empty card">No hay ejercicios para mostrar con estos filtros.</div>'}</div></section>${custom}`
}
function filteredExercises(query='',filter='todos',respectLibrary=false){const q=query.trim().toLowerCase();const fav=favoriteSet();const recent=new Set(state.recentExercises||[]);return state.dataset.filter(ex=>{const alias=aliasesFor(ex.id).join(' ');const txt=`${ex.name} ${ex.target||''} ${ex.equipment||''} ${(ex.secondary_muscles||[]).join(' ')} ${alias}`.toLowerCase();const modeOk=!respectLibrary||state.libraryMode==='all'||(state.libraryMode==='favorites'&&fav.has(ex.id))||(state.libraryMode==='recent'&&recent.has(ex.id));const eqOk=!respectLibrary||equipmentMatches(ex,state.equipmentFilter);return(!q||txt.includes(q))&&(filter==='todos'||ex.body_part===filter)&&modeOk&&eqOk})}
function manualView(){return `<section class="hero"><h1>Manual para empezar</h1><p>Una guía corta para entender la clase y las siglas más comunes.</p></section><section class="section split"><article class="card"><h2>¿Para qué sirve la activación?</h2><p class="muted">Prepara progresivamente músculos, articulaciones y sistema cardiovascular para el trabajo que viene. También sirve para practicar los patrones de movimiento antes de cargar más peso.</p><dl class="glossary"><dt>WOD</dt><dd>Workout of the Day: bloque principal del entrenamiento.</dd><dt>TC / Time Cap</dt><dd>Tiempo máximo para completar un bloque.</dd><dt>REST</dt><dd>Descanso programado.</dd><dt>ESTACIÓN</dt><dd>Bloque corto de tiempo donde se repiten uno o más ejercicios.</dd><dt>COMODÍN</dt><dd>Ejercicio que interrumpe temporalmente la estación cuando se cumple un intervalo, por ejemplo cada 1 minuto.</dd><dt>AMRAP</dt><dd>La mayor cantidad de rondas o repeticiones posibles dentro de un tiempo.</dd><dt>EMOM</dt><dd>Un trabajo que empieza al comienzo de cada minuto.</dd><dt>ALT</dt><dd>Alternado: se cambia lado o brazo.</dd><dt>DB / KB</dt><dd>DB = mancuerna. KB = kettlebell.</dd></dl></article><article class="card"><h2>Regla principal</h2><p class="muted">Primero técnica, después velocidad. Si una carga hace perder postura o control, conviene bajar peso o usar una variante más sencilla.</p><div class="notice warning">La web es una guía. La ejecución y las variantes las define el profesor en clase.</div><h2 style="margin-top:18px">Cómo usar ENTRENA</h2><p class="muted">1. Elegí el día.<br>2. Reservá tu turno.<br>3. Mirá la rutina.<br>4. Tocá cada ejercicio para ver los pasos.<br>5. Si no vas, cancelá el turno.</p></article></section>`}
function profileView(){if(!state.user)return `<section class="hero"><h1>Modo consulta</h1><p>Podés ver el manual y los ejercicios sin cuenta.</p></section><section class="section"><article class="card"><button class="primary-btn" data-action="login">Ingresar para reservar</button></article></section>`;return `<section class="hero"><h1>${h(state.profile?.full_name||state.user.email)}</h1><p>${isStaff()?'Profesor / administrador':'Alumno'} · ${h(state.user.email||'')}</p></section><section class="section"><article class="card"><div class="notice">Los alumnos ven cantidad de cupos. La lista de nombres queda reservada al profesor.</div><button class="danger-btn" style="margin-top:14px" data-action="logout">Cerrar sesión</button></article></section>`}

function adminNav(){const tabs=[['overview','👥 Turnos'],['schedule','🕒 Horarios'],['workout','🔥 Rutina']];return `<div class="admin-tabs">${tabs.map(([k,l])=>`<button class="admin-tab ${state.adminTab===k?'active':''}" data-admin-tab="${k}">${l}</button>`).join('')}</div>`}
function adminView(){if(!isStaff())return profileView();ensureDraft();let body='';if(state.adminTab==='overview')body=adminOverview();if(state.adminTab==='schedule')body=adminSchedule();if(state.adminTab==='workout')body=adminWorkout();return `<section class="hero"><h1>Panel del profesor</h1><p>Administrá cupos, asistentes, horarios y la rutina del día.</p>${dateStrip()}${adminNav()}</section>${messageBar()}${body}`}
function adminOverview(){return `<section class="section"><div class="section-head responsive-head"><div><h2>Turnos del día</h2><div class="section-sub">${fmtDay(state.selectedDay)} · podés sumar a quien avise por WhatsApp</div></div><div class="share-actions"><button class="ghost-btn" data-action="share-day">📤 Compartir</button><button class="ghost-btn" data-action="generate-week">🗓️ Habilitar 7 días</button><button class="primary-btn" data-action="generate-day">Habilitar día</button></div></div><div class="notice" style="margin-bottom:12px">La semana se genera usando solamente los días marcados como activos en <b>Horarios</b>. Si un día ya existe, no se duplica.</div><div class="grid">${state.sessions.map(adminSessionCard).join('')||'<div class="empty card">No hay turnos generados para este día.</div>'}</div></section>`}
function moveSelect(a,fromSession){const opts=state.sessions.filter(s=>s.id!==fromSession&&s.is_open).map(s=>`<option value="${s.id}">${fmtTime(s.start_time)}–${fmtTime(s.end_time)}</option>`).join('');if(!opts)return'';const attr=a.source==='manual'?`data-move-manual="${a.id}"`:`data-move-user="${a.user_id}"`;return `<select class="move-select" ${attr} data-from-session="${fromSession}"><option value="">Mover a…</option>${opts}</select>`}
function attendeeChip(a,sessionId){if(a.source==='manual')return `<span class="person person-manual"><span>${h(a.name)}</span><small>WhatsApp</small>${moveSelect(a,sessionId)}<button class="person-remove" title="Quitar" data-remove-manual="${a.id}">×</button></span>`;return `<span class="person person-user"><span>${h(a.name)}</span>${moveSelect(a,sessionId)}</span>`}
function adminSessionCard(s){const confirmed=(state.attendees[s.id]||[]).filter(a=>a.status==='confirmed');const waiting=(state.attendees[s.id]||[]).filter(a=>a.status==='waitlist');return `<article class="card"><div class="section-head"><div><div class="slot-title">${fmtTime(s.start_time)} — ${fmtTime(s.end_time)}</div><div class="slot-meta">${s.confirmed_count}/${s.capacity} confirmados · ${s.spots_left} libres</div></div><span class="pill ${s.is_open?'ok':'off'}">${s.is_open?'ABIERTO':'CERRADO'}</span></div><div class="attendees">${confirmed.map(a=>attendeeChip(a,s.id)).join('')||'<span class="section-sub">Todavía nadie confirmado.</span>'}</div>${waiting.length?`<div class="waitlist-box"><b>Lista de espera</b><div class="attendees">${waiting.map(a=>attendeeChip(a,s.id)).join('')}</div></div>`:''}<form class="manual-add-form" data-manual-session="${s.id}"><div class="field"><label>Si avisó por WhatsApp</label><input name="display_name" maxlength="100" placeholder="Nombre y apellido" autocomplete="off"></div><button class="ghost-btn" type="submit">+ Agregar</button></form><form class="inline-edit" data-session-cap-form="${s.id}"><div class="field"><label>Cupo de este turno</label><input name="capacity" type="number" min="${Math.max(1,s.confirmed_count)}" max="100" value="${s.capacity}"></div><button class="ghost-btn" type="submit">Guardar</button></form><div class="admin-session-actions"><button class="${s.is_open?'danger-btn':'success-btn'}" data-toggle-session="${s.id}">${s.is_open?'Cerrar inscripciones':'Abrir inscripciones'}</button></div></article>`}
function adminSchedule(){return `<section class="section"><article class="card"><div class="section-head"><div><h2>Días de clase</h2><div class="section-sub">Cuando habilites una semana, sólo se crean turnos en estos días.</div></div></div><form id="weekdaysForm"><div class="weekday-grid">${state.weekdays.map(w=>`<label class="weekday-toggle ${w.active?'active':''}"><input type="checkbox" name="day_${w.iso_day}" ${w.active?'checked':''}><span>${h(w.label)}</span></label>`).join('')}</div><button class="primary-btn" type="submit" style="margin-top:12px">Guardar días de clase</button></form></article><div class="section-head" style="margin-top:18px"><div><h2>Horarios base</h2><div class="section-sub">Estos horarios se usan al habilitar nuevos días. Los turnos ya creados se editan desde “Turnos”.</div></div></div><form id="templatesForm" class="form-grid">${state.templates.map((t,i)=>`<article class="card"><div class="section-head"><div><b>${h(t.label)}</b><div class="section-sub">${h(t.code)}</div></div><span class="pill ${t.active?'ok':'off'}">${t.active?'Activo':'Inactivo'}</span></div><div class="two"><div class="field"><label>Desde</label><input type="time" name="start_${i}" value="${fmtTime(t.start_time)}"></div><div class="field"><label>Hasta</label><input type="time" name="end_${i}" value="${fmtTime(t.end_time)}"></div></div><div class="two" style="margin-top:10px"><div class="field"><label>Cupo</label><input type="number" min="1" max="100" name="cap_${i}" value="${t.capacity}"></div><div class="field"><label>Estado</label><select name="active_${i}"><option value="1" ${t.active?'selected':''}>Activo</option><option value="0" ${!t.active?'selected':''}>Inactivo</option></select></div></div><input type="hidden" name="id_${i}" value="${t.id}"></article>`).join('')}<button class="primary-btn" type="submit">Guardar horarios base</button></form></section>`}
function adminWorkout(){const d=state.draft;const targets=workoutTargets();const formats=[['blocks','WOD por bloques'],['stations','Estaciones'],['amrap','AMRAP'],['emom','EMOM'],['fortime','For Time'],['tabata','Tabata'],['free','Libre']];return `<section class="section"><div class="section-head"><div><h2>Rutina del día</h2><div class="section-sub">${fmtDay(state.selectedDay)} · ${state.workout?.published?'<span class="status-ok">publicada</span>':'borrador / sin publicar'}</div></div><button class="ghost-btn" data-action="preview-workout">👁 Vista alumno</button></div><div class="workout-builder">${routineListHtml()}<article class="card"><div class="section-head"><div><h2>Formato</h2><div class="section-sub">Elegí la estructura que mejor represente la clase.</div></div></div><div class="format-selector">${formats.map(([k,l])=>`<button class="chip ${d.format===k?'active':''}" data-routine-format="${k}">${l}</button>`).join('')}</div><div class="two" style="margin-top:12px"><div class="field"><label>Título</label><input id="draftTitle" value="${h(d.title)}"></div><div class="field"><label>Esquema / reps generales</label><input id="draftReps" value="${h(d.reps)}" placeholder="Ej. 15 · 12 · 9 o 5 rondas"></div></div><div class="field" style="margin-top:10px"><label>Descripción breve</label><textarea id="draftIntro" placeholder="Ej.: Fuerza + acondicionamiento">${h(d.intro)}</textarea></div></article>${d.format==='stations'?stationEditor(d):d.format==='blocks'?blocksEditor(d):simpleEditor(d)}<article class="card"><div class="section-head"><div><h2>Agregar ejercicio</h2><div class="section-sub">Buscalo y mandalo directo a la sección elegida.</div></div></div><div class="builder-target"><select id="builderTarget" class="search">${targets.map(([v,l])=>`<option value="${h(v)}" ${state.builderTarget===v?'selected':''}>${h(l)}</option>`).join('')}</select><button class="${state.datasetLoaded?'ghost-btn':'primary-btn'}" data-action="load-dataset">${state.datasetLoaded?'Base completa ✓':'Cargar base grande'}</button></div><input id="builderSearch" class="search" style="margin-top:10px" placeholder="Buscar ejercicio..." value="${h(state.builderSearch)}"><div id="builderResults" class="builder-search-results" style="margin-top:10px">${builderResultsHtml()}</div></article><div class="builder-actions"><button class="ghost-btn" data-action="save-draft">Guardar borrador</button><button class="ghost-btn" data-action="save-template">⭐ Plantilla</button><button class="primary-btn" data-action="publish-workout">Guardar y publicar</button>${state.workout?'<button class="danger-btn" data-action="unpublish-workout">Despublicar</button>':''}</div></div></section>`}

function builderResultsHtml(){const items=filteredExercises(state.builderSearch,'todos').slice(0,25);if(!state.builderSearch.trim())return '<div class="section-sub">Escribí algo para buscar. También podés usar los ejercicios de ejemplo sin cargar la base completa.</div>';return items.map(ex=>`<div class="builder-result"><div><b>${h(ex.name)}</b><div class="tiny">${h(ex.target||'')} · ${h(ex.equipment||'')}</div></div><button class="mini-btn" data-add-workout="${h(ex.id)}">Agregar</button></div>`).join('')||'<div class="section-sub">No encontré coincidencias.</div>'}

function modalHtml(){
  if(state.previewRoutine){const p=state.previewRoutine;return `<div class="modal-backdrop preview-backdrop" data-action="close-preview"><section class="modal preview-modal" onclick="event.stopPropagation()"><div class="modal-inner"><div class="modal-grab"></div><div class="section-head"><div><h3>Vista previa del alumno</h3><div class="section-sub">Así se verá antes de publicarla.</div></div><button class="mini-btn" data-action="close-preview">Cerrar</button></div>${sampleWorkoutHtml(p.payload,p.title,p.intro)}</div></section></div>`}
  const ex=state.modal;if(!ex)return'';const steps=ex.instruction_steps?.es?.length?ex.instruction_steps.es:(ex.instructions?.es?[ex.instructions.es]:[]);const als=aliasesFor(ex.id);
  return `<div class="modal-backdrop" data-action="close-modal"><section class="modal" onclick="event.stopPropagation()"><div class="modal-inner"><div class="modal-grab"></div><div class="exercise-modal-head"><div class="exercise-thumb" style="width:58px;height:58px;font-size:26px">${iconFor(ex)}</div><button class="favorite-big ${isFavorite(ex.id)?'active':''}" data-favorite="${h(ex.id)}">${isFavorite(ex.id)?'★ Favorito':'☆ Guardar favorito'}</button></div><h3>${h(ex.name)}</h3><div class="muted">Objetivo: ${h(ex.target||'—')} · Equipo: ${h(ex.equipment||'—')}</div>${als.length?`<div class="alias-box"><b>También lo podés buscar como:</b> ${als.map(h).join(' · ')}</div>`:''}<div class="steps">${steps.map(s=>`<div class="step"><div>${h(s)}</div></div>`).join('')}</div><div class="notice warning" style="margin-top:14px">Ejemplo orientativo. Seguí la variante y las correcciones que indique el profesor.</div><div class="modal-actions">${isStaff()?`<button class="ghost-btn" data-add-modal-workout="${h(ex.id)}">➕ Agregar a rutina</button>`:''}<button class="primary-btn" data-action="close-modal">Cerrar</button></div></div></section></div>`
}
function appView(){let content='';if(state.view==='home')content=homeView();if(state.view==='slots')content=slotsView();if(state.view==='library')content=libraryView();if(state.view==='manual')content=manualView();if(state.view==='profile')content=profileView();if(state.view==='admin')content=adminView();return `<div class="app-shell">${topbar()}<main class="container">${content}</main>${nav()}${modalHtml()}</div>`}
function render(){document.getElementById('app').innerHTML=(!state.user&&!state.guest)?authScreen():appView();bind()}

function bind(){
  document.querySelectorAll('[data-auth-tab]').forEach(b=>b.addEventListener('click',()=>{const mode=b.dataset.authTab;document.querySelectorAll('[data-auth-tab]').forEach(x=>x.classList.toggle('active',x===b));const f=document.getElementById('authForm');f.dataset.mode=mode;f.querySelector('.signup-only').style.display=mode==='signup'?'block':'none';f.querySelector('button[type=submit]').textContent=mode==='signup'?'Crear cuenta':'Ingresar';f.querySelector('[name=password]').autocomplete=mode==='signup'?'new-password':'current-password'}));
  document.getElementById('authForm')?.addEventListener('submit',authSubmit);
  document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{state.view=b.dataset.view;render();scrollTo(0,0)}));
  document.querySelectorAll('[data-day]').forEach(b=>b.addEventListener('click',async()=>{captureDraftFromDom();state.selectedDay=b.dataset.day;state.draft=null;state.draftDay=null;await refreshPublic();render()}));
  document.querySelectorAll('[data-exercise]').forEach(b=>b.addEventListener('click',()=>openExercise(b.dataset.exercise)));
  document.querySelectorAll('[data-favorite]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();toggleFavorite(b.dataset.favorite)}));
  document.querySelectorAll('[data-library-mode]').forEach(b=>b.addEventListener('click',()=>{state.libraryMode=b.dataset.libraryMode;render()}));
  document.querySelectorAll('[data-equipment-filter]').forEach(b=>b.addEventListener('click',()=>{state.equipmentFilter=b.dataset.equipmentFilter;render()}));
  document.querySelectorAll('[data-add-modal-workout]').forEach(b=>b.addEventListener('click',()=>{captureDraftFromDom();ensureDraft();addToDraft(b.dataset.addModalWorkout,state.builderTarget);state.modal=null;state.view='admin';state.adminTab='workout';render();setMessage('Ejercicio agregado a la rutina.','notice success')}));
  document.querySelectorAll('[data-reserve]').forEach(b=>b.addEventListener('click',()=>reserve(b.dataset.reserve)));
  document.querySelectorAll('[data-change-reservation]').forEach(b=>b.addEventListener('click',()=>changeReservation(b.dataset.changeReservation)));
  document.querySelectorAll('[data-cancel]').forEach(b=>b.addEventListener('click',()=>cancelRes(b.dataset.cancel)));
  document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{state.filter=b.dataset.filter;render()}));
  document.getElementById('exerciseSearch')?.addEventListener('input',e=>{state.query=e.target.value;const pos=e.target.selectionStart;render();const n=document.getElementById('exerciseSearch');if(n){n.focus();n.setSelectionRange(pos,pos)}});
  document.getElementById('templatesForm')?.addEventListener('submit',saveTemplates);
  document.getElementById('customExerciseForm')?.addEventListener('submit',createCustomExercise);
  document.getElementById('weekdaysForm')?.addEventListener('submit',saveWeekdays);
  document.querySelectorAll('[data-move-user]').forEach(s=>s.addEventListener('change',()=>{if(s.value)moveUserReservation(s.dataset.moveUser,s.dataset.fromSession,s.value)}));
  document.querySelectorAll('[data-move-manual]').forEach(s=>s.addEventListener('change',()=>{if(s.value)moveManualReservation(s.dataset.moveManual,s.value)}));
  document.querySelectorAll('[data-session-cap-form]').forEach(f=>f.addEventListener('submit',saveSessionCapacity));
  document.querySelectorAll('[data-manual-session]').forEach(f=>f.addEventListener('submit',addManualReservation));
  document.querySelectorAll('[data-remove-manual]').forEach(b=>b.addEventListener('click',()=>removeManualReservation(b.dataset.removeManual)));
  document.querySelectorAll('[data-toggle-session]').forEach(b=>b.addEventListener('click',()=>toggleSession(b.dataset.toggleSession)));
  document.querySelectorAll('[data-admin-tab]').forEach(b=>b.addEventListener('click',()=>{captureDraftFromDom();state.adminTab=b.dataset.adminTab;state.view='admin';render();scrollTo(0,0)}));
  document.getElementById('builderTarget')?.addEventListener('change',e=>{state.builderTarget=e.target.value});
  document.querySelectorAll('[data-routine-format]').forEach(b=>b.addEventListener('click',()=>{captureDraftFromDom();state.draft.format=b.dataset.routineFormat;if(state.draft.format==='stations'&&!state.draft.stations.length)state.draft.stations=[{name:'Estación 1',duration:3,note:'',exercises:[]}];if(isSimpleFormat(state.draft.format)&&!state.draft.main)state.draft.main=emptyMain();state.builderTarget='activation';render()}));
  document.querySelectorAll('[data-add-station]').forEach(b=>b.addEventListener('click',()=>{captureDraftFromDom();state.draft.stations.push({name:`Estación ${state.draft.stations.length+1}`,duration:3,note:'',exercises:[]});state.builderTarget=`station:${state.draft.stations.length-1}`;render()}));
  document.querySelectorAll('[data-duplicate-station]').forEach(b=>b.addEventListener('click',()=>{captureDraftFromDom();const i=Number(b.dataset.duplicateStation),src=state.draft.stations[i];if(!src)return;const copy=cloneData(src);copy.name=`${src.name||`Estación ${i+1}`} copia`;state.draft.stations.splice(i+1,0,copy);state.builderTarget=`station:${i+1}`;render()}));
  document.querySelectorAll('[data-remove-station]').forEach(b=>b.addEventListener('click',()=>{captureDraftFromDom();if(state.draft.stations.length>1){state.draft.stations.splice(Number(b.dataset.removeStation),1);state.builderTarget='activation';render()}}));
  document.querySelectorAll('[data-load-preset]').forEach(b=>b.addEventListener('click',()=>loadPreset(Number(b.dataset.loadPreset))));
  document.querySelectorAll('[data-load-history]').forEach(b=>b.addEventListener('click',()=>loadHistory(Number(b.dataset.loadHistory))));
  document.querySelectorAll('[data-load-template]').forEach(b=>b.addEventListener('click',()=>loadCloudTemplate(Number(b.dataset.loadTemplate))));
  document.querySelectorAll('[data-delete-template]').forEach(b=>b.addEventListener('click',()=>deleteRoutineTemplate(b.dataset.deleteTemplate)));
  document.getElementById('builderSearch')?.addEventListener('input',e=>{state.builderSearch=e.target.value;const box=document.getElementById('builderResults');if(box){box.innerHTML=builderResultsHtml();bindBuilderAddButtons()}});
  bindBuilderAddButtons();
  document.querySelectorAll('[data-remove-workout]').forEach(b=>b.addEventListener('click',()=>{captureDraftFromDom();removeFromDraft(b.dataset.removeWorkout,Number(b.dataset.index));render()}));
  document.querySelectorAll('[data-move-item]').forEach(b=>b.addEventListener('click',()=>{captureDraftFromDom();moveDraftItem(b.dataset.target,Number(b.dataset.index),b.dataset.moveItem==='up'?-1:1);render()}));
  bindDragItems();
  document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',async()=>{const a=b.dataset.action;if(a==='guest'){state.guest=true;render()}if(a==='login'){state.guest=false;render()}if(a==='logout'){await sb.auth.signOut();state.guest=false;state.view='home'}if(a==='need-login'){state.guest=false;render()}if(a==='close-modal'){state.modal=null;render()}if(a==='close-preview'){state.previewRoutine=null;render()}if(a==='load-dataset'){await loadFullDataset(b)}if(a==='generate-day'){await generateDay()}if(a==='generate-week'){await generateWeek()}if(a==='share-day'){await shareDay()}if(a==='save-draft'){await saveWorkout(false)}if(a==='publish-workout'){await saveWorkout(true)}if(a==='unpublish-workout'){await saveWorkout(false,true)}if(a==='preview-workout'){previewWorkout()}if(a==='save-template'){await saveRoutineTemplate()}}));
}
function bindBuilderAddButtons(){document.querySelectorAll('[data-add-workout]').forEach(b=>b.addEventListener('click',()=>{captureDraftFromDom();addToDraft(b.dataset.addWorkout,state.builderTarget);render()}))}
function captureDraftFromDom(){if(!isStaff()||!state.draft)return;const title=document.getElementById('draftTitle');if(title)state.draft.title=title.value.trim()||'Entrenamiento del día';const reps=document.getElementById('draftReps');if(reps)state.draft.reps=reps.value.trim();const intro=document.getElementById('draftIntro');if(intro)state.draft.intro=intro.value.trim();document.querySelectorAll('[data-block-tc]').forEach(el=>{const b=blockByName(el.dataset.blockTc);if(b)b.tc=Math.max(0,Number(el.value||0))});document.querySelectorAll('[data-block-rest]').forEach(el=>{const b=blockByName(el.dataset.blockRest);if(b)b.rest=Math.max(0,Number(el.value||0))});document.querySelectorAll('[data-station-name]').forEach(el=>{const s=state.draft.stations[Number(el.dataset.stationName)];if(s)s.name=el.value.trim()||`Estación ${Number(el.dataset.stationName)+1}`});document.querySelectorAll('[data-station-duration]').forEach(el=>{const s=state.draft.stations[Number(el.dataset.stationDuration)];if(s)s.duration=Math.max(1,Number(el.value||3))});document.querySelectorAll('[data-station-note]').forEach(el=>{const s=state.draft.stations[Number(el.dataset.stationNote)];if(s)s.note=el.value.trim()});const je=document.getElementById('jokerEnabled');if(je)state.draft.joker.enabled=je.checked;const jv=document.getElementById('jokerEvery');if(jv)state.draft.joker.every=Math.max(1,Number(jv.value||1));const ji=document.getElementById('jokerInstruction');if(ji)state.draft.joker.instruction=ji.value.trim();if(state.draft.main){const md=document.getElementById('mainDuration');if(md)state.draft.main.duration=Math.max(0,Number(md.value||0));const mr=document.getElementById('mainRounds');if(mr)state.draft.main.rounds=mr.value.trim();const mw=document.getElementById('mainWork');if(mw)state.draft.main.work=Math.max(0,Number(mw.value||0));const mrest=document.getElementById('mainRest');if(mrest)state.draft.main.rest=Math.max(0,Number(mrest.value||0));const mn=document.getElementById('mainNote');if(mn)state.draft.main.note=mn.value.trim()}const patchItem=(target,index,key,value)=>{if(target==='joker'){if(state.draft.joker.exercise)state.draft.joker.exercise=normalizeItem({...normalizeItem(state.draft.joker.exercise),[key]:value});return}const list=getDraftList(target);if(list?.[index])list[index]=normalizeItem({...normalizeItem(list[index]),[key]:value})};document.querySelectorAll('[data-item-reps]').forEach(el=>patchItem(el.dataset.itemReps,Number(el.dataset.index),'reps',el.value.trim()));document.querySelectorAll('[data-item-load]').forEach(el=>patchItem(el.dataset.itemLoad,Number(el.dataset.index),'load',el.value.trim()));document.querySelectorAll('[data-item-note]').forEach(el=>patchItem(el.dataset.itemNote,Number(el.dataset.index),'note',el.value.trim()))}
function getDraftList(target){if(target==='activation')return state.draft?.activation;if(target?.startsWith('block:'))return blockByName(target.split(':')[1])?.exercises;if(target?.startsWith('station:'))return state.draft?.stations?.[Number(target.split(':')[1])]?.exercises;if(target==='main')return state.draft?.main?.exercises;if(target==='joker')return state.draft?.joker?.exercise?[state.draft.joker.exercise]:[];return null}
function addToDraft(id,target){if(!state.draft)return;const item={id,reps:'',load:'',note:''};if(target==='joker'){state.draft.joker.exercise=item;state.draft.joker.enabled=true;return}const list=getDraftList(target);if(!list)return;if(!list.some(x=>itemId(x)===id))list.push(item)}
function removeFromDraft(target,index){if(target==='joker'){state.draft.joker.exercise=null;return}const list=getDraftList(target);if(list&&index>=0)list.splice(index,1)}
function moveDraftItem(target,index,delta){const list=getDraftList(target);if(!list)return;const to=index+delta;if(index<0||to<0||index>=list.length||to>=list.length)return;const [item]=list.splice(index,1);list.splice(to,0,item)}
function bindDragItems(){document.querySelectorAll('[data-builder-item]').forEach(el=>{el.addEventListener('dragstart',e=>{captureDraftFromDom();state.dragInfo={target:el.dataset.builderItem,index:Number(el.dataset.index)};el.classList.add('dragging');e.dataTransfer.effectAllowed='move'});el.addEventListener('dragend',()=>{el.classList.remove('dragging');state.dragInfo=null});el.addEventListener('dragover',e=>{if(state.dragInfo?.target===el.dataset.builderItem){e.preventDefault();e.dataTransfer.dropEffect='move'}});el.addEventListener('drop',e=>{e.preventDefault();const info=state.dragInfo;if(!info||info.target!==el.dataset.builderItem)return;const list=getDraftList(info.target),to=Number(el.dataset.index);if(!list||info.index===to)return;const [item]=list.splice(info.index,1);list.splice(to,0,item);state.dragInfo=null;render()})})}
function loadPreset(index){captureDraftFromDom();const p=routinePresets[index];if(!p)return;state.draft=draftFromPreset(p);state.draftDay=state.selectedDay;state.builderTarget='activation';state.builderSearch='';render();setMessage('Rutina cargada en el editor. Revisala y guardala cuando quieras.','notice success')}
function loadHistory(index){captureDraftFromDom();const row=state.workoutHistory[index];if(!row)return;state.draft=draftFromRow(row);state.draft.title=`${row.title} (copia)`;state.draft.published=false;state.draftDay=state.selectedDay;state.builderTarget='activation';state.builderSearch='';render();setMessage('Rutina anterior copiada al día elegido.','notice success')}
function loadCloudTemplate(index){captureDraftFromDom();const t=state.routineTemplates[index];if(!t)return;state.draft=draftFromRow({title:t.name,intro:t.description||'',payload:t.payload,published:false});state.draftDay=state.selectedDay;state.builderTarget='activation';state.builderSearch='';render();setMessage('Plantilla cargada.','notice success')}
function previewWorkout(){captureDraftFromDom();const d=state.draft;if(!d)return;state.previewRoutine={title:d.title||'Entrenamiento del día',intro:d.intro||'',payload:payloadFromDraft(d)};render()}
async function saveRoutineTemplate(){captureDraftFromDom();const d=state.draft;if(!d||!draftHasExercises(d))return setMessage('Agregá algún ejercicio antes de guardar una plantilla.','notice warning');const suggested=d.title||'Mi plantilla';const name=(window.prompt('Nombre para la plantilla:',suggested)||'').trim();if(!name)return;const description=(window.prompt('Descripción breve (opcional):',formatName(d.format))||'').trim();const {error}=await sb.from('routine_templates').insert({name,description:description||null,payload:payloadFromDraft(d),created_by:state.user.id});if(error){console.error(error);return setMessage('No pude guardar la plantilla.','notice warning')}await loadRoutineTemplates();render();setMessage('Plantilla guardada en la nube.','notice success')}
async function deleteRoutineTemplate(id){const {error}=await sb.from('routine_templates').delete().eq('id',id);if(error)return setMessage('No pude borrar la plantilla.','notice warning');await loadRoutineTemplates();render();setMessage('Plantilla eliminada.','notice success')}


async function createCustomExercise(e){e.preventDefault();if(!isStaff())return;const fd=new FormData(e.currentTarget);const name=String(fd.get('name')||'').trim();if(name.length<2)return setMessage('Escribí un nombre para el ejercicio.','notice warning');const body_part=String(fd.get('body_part')||'').trim()||null,target=String(fd.get('target')||'').trim()||null,equipment=String(fd.get('equipment')||'').trim()||null,instructions=String(fd.get('instructions')||'').trim()||null;const steps=String(fd.get('steps')||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const aliases=String(fd.get('aliases')||'').split(',').map(x=>x.trim()).filter(Boolean);const {data,error}=await sb.from('custom_exercises').insert({name,body_part,target,equipment,instructions,steps,created_by:state.user.id}).select('id').single();if(error){console.error(error);return setMessage('No pude guardar el ejercicio.','notice warning')}if(aliases.length){const rows=aliases.map(alias=>({alias,exercise_key:`db-${data.id}`,created_by:state.user.id}));const {error:ae}=await sb.from('exercise_aliases').insert(rows);if(ae)console.error(ae)}await loadExerciseLibraryMeta();state.query=name;e.currentTarget.reset();render();setMessage('Ejercicio agregado a la biblioteca.','notice success')}

async function authSubmit(e){e.preventDefault();const f=e.currentTarget,fd=new FormData(f),email=String(fd.get('email')).trim(),password=String(fd.get('password')),mode=f.dataset.mode||'login';if(mode==='signup'){const full_name=String(fd.get('full_name')||'').trim();const {data,error}=await sb.auth.signUp({email,password,options:{data:{full_name}}});if(error)return setMessage(error.message,'notice warning');if(!data.session)return setMessage('Cuenta creada. Revisá tu correo para confirmar y después ingresá.','notice success')}else{const {error}=await sb.auth.signInWithPassword({email,password});if(error)return setMessage('No pude ingresar. Revisá correo y contraseña.','notice warning')}}
async function reserve(id){const {data,error}=await sb.rpc('reserve_session',{p_session_id:id});if(error){const m=error.message.includes('already_reserved_other_slot')?'Ya tenés otro turno reservado para ese día. Usá “Cambiarme” para pasar a otro horario.':error.message.includes('session_not_available')?'Ese turno ya no está disponible.':'No pude hacer la reserva.';return setMessage(m,'notice warning')}await refreshPublic();setMessage(data==='waitlist'?'El turno está completo: quedaste en lista de espera.':'Listo, tu lugar quedó reservado.','notice success')}
async function changeReservation(id){const {data,error}=await sb.rpc('change_reservation',{p_session_id:id});if(error){const m=error.message.includes('session_not_available')?'Ese turno está cerrado.':'No pude cambiarte de horario.';return setMessage(m,'notice warning')}await refreshPublic();setMessage(data==='waitlist'?'Te cambiaste de horario y quedaste en lista de espera.':'Listo, te cambiaste de horario.','notice success')}
async function cancelRes(id){const {error}=await sb.rpc('cancel_reservation',{p_session_id:id});if(error)return setMessage('No pude cancelar la reserva.','notice warning');await refreshPublic();setMessage('Reserva cancelada y cupo liberado.','notice success')}
async function addManualReservation(e){e.preventDefault();const f=e.currentTarget;const sessionId=f.dataset.manualSession;const name=String(new FormData(f).get('display_name')||'').trim();if(name.length<2)return setMessage('Escribí el nombre de la persona.','notice warning');const {data,error}=await sb.rpc('add_manual_reservation',{p_session_id:sessionId,p_display_name:name});if(error){const msg=error.message.includes('manual_name_already_added')?'Esa persona ya está agregada en este turno.':'No pude agregar a esa persona.';return setMessage(msg,'notice warning')}f.reset();await refreshPublic();setMessage(data==='waitlist'?`${name} quedó en lista de espera.`:`${name} quedó anotado en el turno.`,'notice success')}
async function removeManualReservation(id){const {error}=await sb.rpc('remove_manual_reservation',{p_manual_id:id});if(error)return setMessage('No pude quitar esa anotación.','notice warning');await refreshPublic();setMessage('Anotación manual quitada.','notice success')}
async function shareDay(){if(!state.sessions.length)return setMessage('Primero habilitá los turnos de ese día.','notice warning');const lines=state.sessions.map(s=>`${fmtTime(s.start_time)}–${fmtTime(s.end_time)} · ${s.confirmed_count}/${s.capacity} anotados${s.spots_left?` · ${s.spots_left} libres`:' · completo'}`);const base=location.href.split('#')[0].split('?')[0];const text=`🏋️ Turnos ${fmtDay(state.selectedDay)}\n\n${lines.join('\n')}\n\nAnotate acá 👇\n${base}`;try{if(navigator.share){await navigator.share({title:'ENTRENA · Turnos',text});return}if(navigator.clipboard){await navigator.clipboard.writeText(text);setMessage('Mensaje copiado. Pegalo en el grupo de WhatsApp.','notice success');return}}catch(err){if(err?.name==='AbortError')return;console.error(err)}window.open(`https://wa.me/?text=${encodeURIComponent(text)}`,'_blank')}
async function generateWeek(){const {data,error}=await sb.rpc('generate_sessions_for_week',{p_start:state.selectedDay});if(error)return setMessage('No pude habilitar la semana. Revisá los días y horarios base.','notice warning');await refreshPublic();setMessage(data?`Semana habilitada: ${data} turnos nuevos.`:'La semana ya estaba habilitada o no hay días activos.','notice success')}
async function saveWeekdays(e){e.preventDefault();const fd=new FormData(e.currentTarget);for(const w of state.weekdays){const active=fd.get(`day_${w.iso_day}`)==='on';const {error}=await sb.from('class_weekdays').update({active,updated_at:new Date().toISOString()}).eq('iso_day',w.iso_day);if(error){console.error(error);return setMessage('No pude guardar los días de clase.','notice warning')}}await refreshPublic();render();setMessage('Días de clase guardados.','notice success')}
async function moveUserReservation(userId,fromSession,toSession){const {data,error}=await sb.rpc('move_reservation',{p_user_id:userId,p_from_session:fromSession,p_to_session:toSession});if(error)return setMessage('No pude mover a esa persona.','notice warning');await refreshPublic();setMessage(data==='waitlist'?'Persona movida a lista de espera.':'Persona movida al nuevo horario.','notice success')}
async function moveManualReservation(manualId,toSession){const {data,error}=await sb.rpc('move_manual_reservation',{p_manual_id:manualId,p_to_session:toSession});if(error)return setMessage('No pude mover esa anotación de WhatsApp.','notice warning');await refreshPublic();setMessage(data==='waitlist'?'Anotación movida a lista de espera.':'Anotación movida al nuevo horario.','notice success')}
async function generateDay(){const {error}=await sb.rpc('generate_sessions_for_day',{p_day:state.selectedDay});if(error)return setMessage('No pude habilitar los turnos. Verificá que tu cuenta tenga rol de profesor.','notice warning');await refreshPublic();setMessage('Turnos habilitados para el día elegido.','notice success')}
async function toggleSession(id){const s=state.sessions.find(x=>x.id===id);if(!s)return;const {error}=await sb.from('class_sessions').update({is_open:!s.is_open}).eq('id',id);if(error)return setMessage('No pude cambiar el estado del turno.','notice warning');await refreshPublic();setMessage(!s.is_open?'Inscripciones abiertas.':'Inscripciones cerradas.','notice success')}
async function saveSessionCapacity(e){e.preventDefault();const id=e.currentTarget.dataset.sessionCapForm;const s=state.sessions.find(x=>x.id===id);const cap=Number(new FormData(e.currentTarget).get('capacity'));if(!s||!Number.isFinite(cap)||cap<Math.max(1,s.confirmed_count))return setMessage(`El cupo no puede ser menor a ${s?.confirmed_count||1}.`,'notice warning');const {error}=await sb.from('class_sessions').update({capacity:cap}).eq('id',id);if(error)return setMessage('No pude guardar el cupo.','notice warning');await refreshPublic();setMessage('Cupo actualizado para ese turno.','notice success')}
async function saveTemplates(e){e.preventDefault();const fd=new FormData(e.currentTarget);for(let i=0;i<state.templates.length;i++){const id=fd.get(`id_${i}`),active=fd.get(`active_${i}`)==='1',start=fd.get(`start_${i}`)||null,end=fd.get(`end_${i}`)||null,capacity=Number(fd.get(`cap_${i}`)||10);if(active&&(!start||!end))return setMessage('Para activar un turno tenés que completar desde y hasta.','notice warning');if(start&&end&&start>=end)return setMessage('La hora de inicio tiene que ser anterior a la de fin.','notice warning');const {error}=await sb.from('class_templates').update({start_time:start,end_time:end,capacity,active}).eq('id',id);if(error){console.error(error);return setMessage('No pude guardar los horarios.','notice warning')}}await refreshPublic();setMessage('Horarios base guardados.','notice success')}
async function saveWorkout(published=false,unpublish=false){captureDraftFromDom();const d=state.draft;if(!d)return;if(published&&!draftHasExercises(d))return setMessage('Agregá por lo menos un ejercicio antes de publicar.','notice warning');const row={day:state.selectedDay,title:d.title||'Entrenamiento del día',intro:d.intro||null,payload:payloadFromDraft(d),published:unpublish?false:published,created_by:state.user.id};const {error}=await sb.from('workouts').upsert(row,{onConflict:'day'});if(error){console.error(error);return setMessage('No pude guardar la rutina.','notice warning')}await refreshPublic();ensureDraft(true);setMessage(unpublish?'Rutina despublicada.':published?'Rutina publicada para los alumnos.':'Borrador guardado.','notice success')}

async function loadFullDataset(btn){if(state.datasetLoaded)return;const old=btn.textContent;btn.textContent='Cargando…';btn.disabled=true;try{let data=await idbGet('exercises-v1');if(!data){const r=await fetch(DATASET_URL,{cache:'force-cache'});if(!r.ok)throw new Error();data=await r.json();await idbSet('exercises-v1',data)}const mapped=data.map(x=>({id:`gh-${x.id}`,name:x.name,body_part:x.body_part,equipment:x.equipment,target:x.target,secondary_muscles:x.secondary_muscles||[],instructions:{es:x.instructions?.es||''},instruction_steps:{es:x.instruction_steps?.es||[]}}));state.dataset=[...demoExercises,...(state.customExercises||[]).map(customRowToExercise),...mapped];state.datasetLoaded=true;state.query='';render();setMessage(`Base completa cargada: ${mapped.length} ejercicios.`,'notice success')}catch(err){console.error(err);setMessage('No pude cargar la base completa. Revisá Internet e intentá de nuevo.','notice warning');btn.textContent=old;btn.disabled=false}}
function idbOpen(){return new Promise((resolve,reject)=>{const req=indexedDB.open('entrena-cache',1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains('kv'))req.result.createObjectStore('kv')};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function idbGet(key){try{const db=await idbOpen();return await new Promise((resolve,reject)=>{const tx=db.transaction('kv','readonly');const r=tx.objectStore('kv').get(key);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}catch{return null}}
async function idbSet(key,val){try{const db=await idbOpen();return await new Promise((resolve,reject)=>{const tx=db.transaction('kv','readwrite');tx.objectStore('kv').put(val,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}catch{}}

if('serviceWorker'in navigator){addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
init().catch(err=>{console.error(err);document.getElementById('app').innerHTML='<div class="login-wrap"><div class="login-card"><h1>ENTRENA</h1><p>No pude iniciar la conexión. Revisá Internet y recargá.</p></div></div>'});
